### ISSUE TITLE
FYI: Problem with .NET Core 3.0.0-preview-27324-5

### ISSUE THREAD

**Issue by jhu78** [allansson/parcel-aspnetcore-middleware#1]
I get a System.MissingMethodException when invoking UseParcelBundler. Full stacktrace is:

```
System.MissingMethodException: Method not found: 'Void Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor(System.String, System.Func`3<System.String,Microsoft.Extensions.Logging.LogLevel,Boolean>, Boolean)'.
   at Microsoft.AspNetCore.NodeServices.NodeServicesOptions..ctor(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.ParcelBundlerApplicationBuilderExtensions.UseParcelBundler(IApplicationBuilder app, ParcelBundlerOptions options)
   at Xplorers.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\[...]\Startup.cs:line 45

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by TenCoKaciStromy** [comment]
I just created PR - [Update to .NET Core 3.0](https://github.com/allansson/parcel-aspnetcore-middleware/pull/3).

**Comment by macupryk** [comment]
I Installed Microsoft.AspNetCore.SpaServices.Extensions V3.0.0. seems to resolve issue.
